services:
  clickhouse:
    image: clickhouse:24.10.2.80
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: manyevents
      CLICKHOUSE_USER: username
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: manyevents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - 5432:5432

volumes:
  clickhouse_data:
  clickhouse_config:
