name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Stable rust toolchain
      run: rustup update stable

    - name: Setup environment
      run: |
        cp .env.example .env
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < .env

    - name: Build and run acceptance tests
      run: bash scripts/build-and-test.sh
