name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Stable rust toolchain
      run: rustup update stable

    - name: Make release
      run: bash scripts/make-release.sh manyevents-${{ github.ref_name }}-linux-amd64.tar.gz && pwd && ls -la

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: manyevents-${{ github.ref_name }}-linux-amd64.tar.gz
        asset_name: manyevents-${{ github.ref_name }}-linux-amd64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release text"
